"""
================================================================================
SYSTEM PROMPT FOR OPUS 4.6 (ORCHESTRATOR LLM)
================================================================================

[ROLE & OBJECTIVE]
You are the Cognitive Routing and Generation Engine for a pan-India telephonic IVR system. 
Your primary objective is to receive raw, transcribed user speech (often containing code-switching, grammatical errors, and regional slang), analyze the underlying intent, and generate a culturally and linguistically appropriate response that will be fed directly to a regional Text-to-Speech (TTS) engine.

[POSITION IN ARCHITECTURE FLOW]
1. Caller -> Asterisk PBX (Raw Audio)
2. Colab Server -> Faster-Whisper (Generates raw text) + IndicBERT (Intent) + Wav2Vec (Accent Profile)
3. -> [YOU ARE HERE] <- You receive the JSON packet from the Colab Server.
4. You -> Regional TTS Engine (Your output drives the synthesized voice)
5. TTS Audio -> Asterisk PBX -> Caller

[INPUT CONTEXT SCHEMA]
You will receive a JSON payload containing:
- `raw_text`: The exact transcription (e.g., "Mera network kaam nahi kar raha hai, please fix it.")
- `language`: Detected primary base language (e.g., "hi", "ta", "mr").
- `detected_profile`: The caller's regional accent mapping (e.g., "hi_mumbai", "ta_chennai").
- `intent_data`: Pre-classified category and urgency (e.g., {"category": "Network_Issue", "urgency": "High"}).

[EXECUTION RULES]
1. EMPATHY & URGENCY: If the `intent_data` marks urgency as "High", immediately acknowledge the frustration in your response before offering a solution.
2. LINGUISTIC MIRRORING: You must generate the response in the exact language/dialect mapped to the `detected_profile`. 
    - If "hi_mumbai", use colloquial terms (e.g., "Tension mat lijiye").
    - If "hi_rural_up", use formal, respectful Hindi (e.g., "Kshama chahenge, hum iski jaanch kar rahe hain").
3. TTS OPTIMIZATION: Write responses out phonetically if dealing with English acronyms (e.g., write "A T and T" instead of "AT&T") to prevent the regional TTS engine from glitching.
4. BREVITY: This is a live phone call. Keep responses under 15 seconds of spoken time (roughly 2-3 short sentences).

[OUTPUT SCHEMA]
You must strictly output a valid JSON response with no markdown formatting or conversational filler:
{
    "tts_script": "The exact string to be synthesized.",
    "suggested_action": "handoff_to_human" | "resolve_automated" | "ask_followup",
    "tts_overrides": {
        "emotion": "calm" | "apologetic" | "helpful"
    }
}
================================================================================
"""

import asyncio
import websockets
import json
import wave
import time
import os

# Configuration
# Replace this with the ngrok URL generated by your Colab notebook
COLAB_WEBSOCKET_URL = "ws://YOUR_NGROK_URL.ngrok.app/stream"
TEST_AUDIO_FILE = "test_hindi_complaint.wav" 

async def mock_llm_processing(pipeline_data):
    """
    This function simulates passing the Colab pipeline data to your LLM (e.g., Claude/Opus API)
    using the system prompt defined at the top of this file.
    """
    print("\n--- Sending data to Orchestrator LLM ---")
    print(f"Context provided to LLM: {json.dumps(pipeline_data, indent=2)}")
    
    # In production, you would make your anthropic.messages.create() call here,
    # passing the massive system prompt and the pipeline_data as the user message.
    
    # Mock LLM Response based on the system prompt rules
    mock_llm_response = {
        "tts_script": "Mafi chahenge sir. Hum aapke network issue ko abhi check kar rahe hain.",
        "suggested_action": "resolve_automated",
        "tts_overrides": {
            "emotion": "apologetic"
        }
    }
    
    print("\n--- LLM Output (Ready for TTS) ---")
    print(json.dumps(mock_llm_response, indent=2))
    return mock_llm_response

async def stream_audio_to_pipeline():
    """
    Acts as the Asterisk/AGI client. Reads a local audio file and streams it 
    to the Colab WebSocket server in chunks, exactly like a live phone call.
    """
    if not os.path.exists(TEST_AUDIO_FILE):
        print(f"Error: Please place a 16kHz, 16-bit Mono WAV file named '{TEST_AUDIO_FILE}' in this directory.")
        return

    async with websockets.connect(COLAB_WEBSOCKET_URL) as websocket:
        print(f"Connected to Unified Pipeline: {COLAB_WEBSOCKET_URL}")
        
        with wave.open(TEST_AUDIO_FILE, 'rb') as wf:
            # Verify audio format (must match Asterisk's 8kHz or 16kHz raw PCM)
            framerate = wf.getframerate()
            print(f"Streaming audio at {framerate}Hz...")

            # Stream chunks of audio (e.g., 4000 frames at a time)
            chunk_size = 4000 
            data = wf.readframes(chunk_size)

            while data:
                # 1. Send raw bytes to Colab
                await websocket.send(data)
                
                # 2. Briefly wait to simulate real-time talking speed
                await asyncio.sleep(chunk_size / framerate)
                
                # 3. Check if Colab has sent back a transcription/intent packet
                try:
                    # Non-blocking receive
                    response = await asyncio.wait_for(websocket.recv(), timeout=0.1)
                    pipeline_data = json.loads(response)
                    
                    print("\n[✔] Pipeline Processed a Chunk!")
                    print(f"User Said: {pipeline_data.get('text')}")
                    print(f"Detected Profile: {pipeline_data.get('detected_profile', {}).get('lang')}")
                    
                    # 4. Trigger the LLM with the extracted data
                    await mock_llm_processing(pipeline_data)
                    
                except asyncio.TimeoutError:
                    # No response yet, keep sending audio
                    pass
                
                data = wf.readframes(chunk_size)
                
        print("\nFinished streaming audio file.")

if __name__ == "__main__":
    try:
        asyncio.run(stream_audio_to_pipeline())
    except KeyboardInterrupt:
        print("Streaming stopped manually.")
    except Exception as e:
        print(f"Connection failed: {e}")
