[general]
static=yes
writeprotect=no

[internal]
exten => 1001,1,Dial(SIP/1001,30,r)
 same => n,Hangup()

exten => 1002,1,Dial(SIP/1002,30,r)
 same => n,Hangup()

exten => 2000,1,Answer()
 same => n,Wait(1)
 same => n,Set(TIMESTAMP=${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)})
 same => n,Playback(hello-world)
 same => n,Wait(1)
 same => n,Record(/var/lib/asterisk/sounds/recordings/${CALLERID(num)}-${TIMESTAMP}.gsm,,,120,#)
 same => n,Playback(thank-you)
 same => n,Hangup()

[default]
exten => 1001,1,Dial(SIP/1001,30,r)
 same => n,Hangup()

exten => 1002,1,Dial(SIP/1002,30,r)
 same => n,Hangup()

exten => 2000,1,Answer()
 same => n,Wait(1)
 same => n,Set(TIMESTAMP=${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)})
 same => n,Playback(hello-world)
 same => n,Wait(1)
 same => n,Record(/var/lib/asterisk/sounds/recordings/${CALLERID(num)}-${TIMESTAMP}.gsm,,,120,#)
 same => n,Playback(thank-you)
 same => n,Hangup()

exten => _X.,1,Hangup()